### ISSUE TITLE
Crash when entering a Warp Painting

### ISSUE THREAD

**Issue by Wolris** [dayofpi/super-block-world#1]
Picked up the star, server booted me.  Re-entered server, entered the painting, server just booted me and shut down.
Crash log: https://mcpaste.io/c7284bb805dfc2c3

Was in creative mode at the time

**Comment by Wolris** [comment]
Oh, and here's the server logs: https://mcpaste.io/8322c54e58cb79cf

Line 352 is where I log in, my character was still jumping at thte Warp Painting, so it immediately tried to send me to the dimension and failed.

**Comment by Wolris** [comment]
This update actually caused the server to fail on load.  I tried it with and without other mods: https://mcpaste.io/55ac022a7cecea26

**Comment by Wolris** [comment]
One other notable thing, It crashes when I pick up any loose item, not just the star.

**Comment by dayofpi** [comment]
It might be a separate issue, yeah. I just released another version, does it fix the other crash?

**Comment by dayofpi** [comment]
0.0.5 should have both issues fixed

**Comment by Wolris** [comment]
0.0.4 fixed Server Dimension Jumping... Testing 0.0.5 now

**Comment by Wolris** [comment]
Excellent, 0.0.5 worked just fine, too!  No problems travelling, no problems picking things up.
