### ISSUE TITLE
half of the items are missing?

### ISSUE THREAD

**Issue by sliceofblu** [dayofpi/super-block-world#15]
i downloaded the mod because it looked fun, not to mention all the nice mobs and little touches, and while some of those stayed intact like half of the items in the mod were gone when i downloaded it. Jump shoes, plumbers cap, a bunch of spawn eggs and most likely more

has this question been answered already or am i just doing something wrong? i'm on 1.20.1, using modrinth (forge) and have tried most everything i can think of

**Comment by xXDasherGamerXx** [comment]
The creator is currently gonna rewrite all of the items, blocks, mobs, etc., for the forge modloader, cuz I don't think they can just straight up port everything from the fabric version straight to the forge modloader, due to the vast, major differences between the two.

It'll take some time to get everything remade for the forge version. Hopefully this helps answer ur question :D

**Comment by sliceofblu** [comment]
> The creator is currently gonna rewrite all of the items, blocks, mobs, etc., for the forge modloader, cuz I don't think they can just straight up port everything from the fabric version straight to the forge modloader, due to the vast, major differences between the two.
> 
> It'll take some time to get everything remade for the forge version. Hopefully this helps answer ur question :D

wait there's a fabric version with all of it???? where??????? i thought it was only on forge (lmao i dunno how to reply to other replies on github if i can sorry)

**Comment by sliceofblu** [comment]
thanks i didnt know that lol

**Comment by xXDasherGamerXx** [comment]
> > The creator is currently gonna rewrite all of the items, blocks, mobs, etc., for the forge modloader, cuz I don't think they can just straight up port everything from the fabric version straight to the forge modloader, due to the vast, major differences between the two.
> > It'll take some time to get everything remade for the forge version. Hopefully this helps answer ur question :D
> 
> wait there's a fabric version with all of it???? where??????? i thought it was only on forge (lmao i dunno how to reply to other replies on github if i can sorry)

Mhmm, they originally made it for Fabric before deciding to drop it FOR NOW, to make a Forge version of it

Here: https://www.curseforge.com/minecraft/mc-mods/super-block-world-classic

**Comment by xXDasherGamerXx** [comment]
> thanks i didnt know that lol

All good chief lol
