### ISSUE TITLE
Invincible Boom Boom

### ISSUE THREAD

**Issue by Ethanthelandlord92** [dayofpi/super-block-world#6]
I have encountered a Boom Boom and when I try to kill it, it doesn't take any damage. I tried using almost every trick in the book, and nothing worked.

**Comment by dayofpi** [comment]
Did you have any other mods installed? And did this happen again with any other Boom Boom? I haven't been able to recreate this issue

**Comment by Ethanthelandlord92** [comment]
I didn't know what mod that was responsible for the invincibility, but the invincibility also happened to other mobs as well, I fixed the problem already.
